### ISSUE TITLE
typeahead:initialized event gone

### ISSUE THREAD

**Issue by cruiser12** [corejavascript/typeahead.js#111]
Hello,

with 0.9 i still had this event, but i guess since the suggestion engine was moved out of the typeahead core, i dont have this event anymore. I also cannot find an prefetch event in bloodhound api. Is there a good solution for it ?

Kind regards

Chris

**Comment by jlbooker** [comment]
Hi @cruiser12,

It looks like this event was moved to the suggestion-engine level, and is available for initializing each data source. See: https://github.com/corejavascript/typeahead.js/blob/master/doc/bloodhound.md#bloodhoundinitializereinitialize

Like that example, you'll probably want to attach a function using `.done()` to the promise that's returned by calling `engine.initialize()`.
