### ISSUE TITLE
limit parameter not working

### ISSUE THREAD

**Issue by frankmeyerpfauder** [corejavascript/typeahead.js#114]
I recently upgraded a site from typeahead 0.10.5 to 1.0.1 (and today 1.1.1). Before, typeahead would correctly display all matching results. Ever since 1.0.1, only 5 results are being shown at any given time, even if I change the limit parameter. I had a look at the source code output, and found out that Bloodhound does indeed return all valid results, so the problem is related to typeahead.js itself.

After digging a bit into the source code, I found this line (1671):

`            this.limit = o.limit || 5;`

If setting the value manually to something big at that line, all results are shown. Also, it looks like o.limit comes as undefined when reaching that line, even tough it's specified as argument:

```
$('#element').typeahead(
    {
        hint: true,
        highlight: true,
        minLength: 1,
  	limit: 30
    },
    {
        source: numbers
    })
```

This issue is browser independant, and even though I'm aware the whole code is in kind of an old environment (jQuery 2.1.3) with quite a few other scripts, it still is kind of weird, as with the older version it worked just fine.

Any more precise way to track if that parameter value is being read correctly or just being ignored?

**Comment by neofreko** [comment]
You should move the `limit` key to the second param object like this:
```
$('#element').typeahead(
    {
        hint: true,
        highlight: true,
        minLength: 1
    },
    {
        source: numbers,
        limit: 30
    })
```

**Comment by frankmeyerpfauder** [comment]
Thanks a lot, now that explains it, glad it was just me not looking correctly into the docs!
