### ISSUE TITLE
Remove help text

### ISSUE THREAD

**Issue by vlahanas** [corejavascript/typeahead.js#115]
Hello,
how can i totally remove help text such as "5 results are available, use up and down arrow keys to navigate." ? I would prefer a non-css (ex. display:hidden; ) solution.

thanks in advance

**Comment by ricardobrandao** [comment]
You might want to take a look at this [PR](https://github.com/corejavascript/typeahead.js/pull/107)

**Comment by jlbooker** [comment]
@vlahanas Try the latest v.1.1.1 release. The help text should be hidden.

**Comment by vlahanas** [comment]
thank you both @jlbooker @ricardobrandao
