### ISSUE TITLE
What about algolia/autocomplete.js ?

### ISSUE THREAD

**Issue by bitcity** [corejavascript/typeahead.js#12]
Algolia was using typeahead.js until they switched to an in-house solution :  https://github.com/algolia/autocomplete.js/issues/5 

Would it make sense to focus our energies on algolia branch or does this have a USP over it ?

**Comment by jlbooker** [comment]
Algolia seems like a viable alternative, but I think I'll continue to support this project. I'll continue to fix issues and merge the pending pull requests as I can.

Closing this for now, since it's pretty old.
