### ISSUE TITLE
Documentation for Bloodhound

### ISSUE THREAD

**Issue by jotatoledo** [corejavascript/typeahead.js#122]
Hi,

first of all thanks for maintaining this awesome library!
Just wanted to note, that the configuration option related to "cache" under "remote" is missing. 

For example:

```
var keywords = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.whitespace,
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            remote: {
                url: `${urlWords}?term=%QUERY`,
                wildcard: '%QUERY',
                cache : false
            }
        });
```

Would be nice if it could be added.

**Comment by holtkamp** [comment]
You mean in this section? https://github.com/corejavascript/typeahead.js/blob/master/doc/bloodhound.md#remote

What does the ```cache``` option do exactly, maybe *you* can provide a PR that adds some explanation on what it does? 😄 

Guess these parts are relevant
https://github.com/corejavascript/typeahead.js/blob/47d46b40cb834d8285ac9328c4b436e5eccf7197/src/bloodhound/remote.js#L20
https://github.com/corejavascript/typeahead.js/blob/47d46b40cb834d8285ac9328c4b436e5eccf7197/src/bloodhound/transport.js#L27
https://github.com/corejavascript/typeahead.js/blob/47d46b40cb834d8285ac9328c4b436e5eccf7197/src/bloodhound/lru_cache.js

**Comment by jotatoledo** [comment]
Hi,
yes I meant exactly that section of the documentation,

Situation:
I was using an input field with autocomplete for keywords. The user was able to submit a form with a set of new/old keywords. If the caching was turned on, previously added new keywords were not displayed without refreshing the complete page.

I would like to add this in the doc but I have no idea how to make prs : D.

**Comment by holtkamp** [comment]
>I would like to add this in the doc but I have no idea how to make prs : D.

Very simple! Go to the documentation and press the edit button, make the edits, submit the PR 😄 

![screen shot 2017-02-26 at 12 45 33](https://cloud.githubusercontent.com/assets/776405/23339405/bbc023a0-fc21-11e6-9074-de8dc2d9854c.png)
