### ISSUE TITLE
Typeahed UI config

### ISSUE THREAD

**Issue by jotatoledo** [corejavascript/typeahead.js#123]
Hi, 
is there any way to remove/turn off /modify the helper message displayed on the input field element?
I mean the message with 

(length + " " + words.result + " " + words.is + " available, use up and down arrow keys to navigate.");

I haven't found something related to this in the documentation.

Thanks!

**Comment by svbergerem** [comment]
Sounds like a duplicate of #115.

**Comment by jotatoledo** [comment]
Hi,
thanks for the reply! Ill take a closer look later :+1:

**Comment by jotatoledo** [comment]
Updating to the last version solved the problem, as pointed on #115.
Thx!
