### ISSUE TITLE
Not all results shown if less than limit

### ISSUE THREAD

**Issue by skwalker** [corejavascript/typeahead.js#124]
(originally filed as https://github.com/twitter/typeahead.js/issues/1232)

The fix for this is to swap two lines [here](https://github.com/corejavascript/typeahead.js/blob/master/src/typeahead/dataset.js#L277):
`rendered += idx;` should be after `that._append`

Thanks!

**Comment by jlbooker** [comment]
I believe this was reported in this fork in #43 and fixed in #52 . Are you sure you're using the latest version?

**Comment by skwalker** [comment]
Yep, it started working, thanks!
