### ISSUE TITLE
Suggestions are displayed twice when using Bloodhound remote option

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [corejavascript/typeahead.js#139]
Either the configuration of my typeahead input is wrong or the plugin has serious issues with remote calls (Bloodhound remote option). 

Here is the repo:

- request the page
- typing `A` in the input -> remote request is excuted
- server receives the request and returns `A`, `B`, `C` (it does not filter for the query term on purpose)
- the remote data is processed
- suggestion popup is displayed with `A`
- typing something in the input again -> remote request is excuted
- server receives the request and returns `A`, `B`, `C` (same behavior as above)
- the remote data is processed
- suggestion data is simply **appended** to the popup without any additional checks or existing suggestion processing -> everything is displayed twice, in this case `A`, `A`

The cause of this is the following [line](https://github.com/corejavascript/typeahead.js/blob/master/src/typeahead/dataset.js#L278) in 
`typeahead.js`:

    that._append(query, suggestions.slice(0, idx));

I've tried to add some code that analyzes the existing suggestions in the popup but i could not find a way to get to the `Menu` instance. As a last resort solution i've added the following line

    that._resetLastSuggestion();

before the append call and now the popup works again as expected.

Is this a valid approach? Should i provide a PR?

**Comment by jlbooker** [comment]
@ViRuSTriNiTy I haven't been able to reproduce this. I have multiple different typeahead instances running where the suggestions are replaced completely (without duplication) as the user types.

Could you create a JSFiddle demo that reproduces the problem?

**Comment by jlbooker** [comment]
Possibly related to #103. Are you using both prefetch and remote sources?

**Comment by jlbooker** [comment]
May also be a duplicate of #59

**Comment by ViRuSTriNiTy** [comment]
Issue resolved in connection with #140, the remote source was not providing the suggestions based on the query term.
