### ISSUE TITLE
Wrong suggestions are displayed when using Bloodhound remote option

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [corejavascript/typeahead.js#140]
repro

- request page
- input gets initialized with limit `3`
- typing `D` something into the input -> remote request is excuted
- server receives the request and returns `A`, `B`, `C`, `D` (it does not filter for the query term on purpose, that's why `A`, `B`, `C` is also returned)
- the remote data is processed by typeahead
- suggestion popup is displayed with `A`, `B`, `C`

The 3 suggestions seem correct at first look as limit `3` is set but `D` would be the correct suggestion here as i typed `D` into the input.

The cause of this is the following [line](https://github.com/corejavascript/typeahead.js/blob/master/src/bloodhound/bloodhound.js#L169) in `bloodhound.js`:

    function processRemote(remote) {
      ...

      async(nonDuplicates); // *1
    }

`*1` passes the suggestions to the `async` callback of `typeahead.js` without filtering the suggestions before (like it is normally done on sync requests).

By adding the following line

    nonDuplicates = that.sorter(that.index.search(query));

before the `async` call it is now ensured that the suggestions match the query.

The input now displays `D` correctly whereas also `A`, `B`, `C` is in the index for further searches (when Bloodhound is configured with `indexRemote`).

Is this a valid approach? If so, should i provide a PR?

**Comment by jlbooker** [comment]
Your remote source must filter the results and return only suggestions that match the query in some way.

See twitter/typeahead.js#248, twitter/typeahead.js#808, twitter/typeahead.js#148

**Comment by ViRuSTriNiTy** [comment]
Ok, remote source now filters and it works.
