### ISSUE TITLE
Bloodhound is not defined

### ISSUE THREAD

**Issue by creativetags** [corejavascript/typeahead.js#145]
I'm trying to install typeahead.js and I can't get past the console error Uncaught ReferenceError: Bloodhound is not defined. I've linked the typeahead.bundle.min.js so I'm guessing there's something else I need to do before I can call var bloodhound = new Bloodhound(

Is it something to do with require.js ? I don't use this and don't want to learn it so would rather the solution was here's what you need to do to avoid needing that.

**Comment by ViRuSTriNiTy** [comment]
What does your source code look like?

**Comment by creativetags** [comment]
Sorry, looks like it was an issue with Turbolinks. when I wrapped my code in document.addEventListener("turbolinks:load", function() {}) it worked as expected.

**Comment by simplenotezy** [comment]
I have this error as well.

    import 'corejs-typeahead/dist/typeahead.bundle.min.js';

		var results = new Bloodhound({
			datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
			queryTokenizer: Bloodhound.tokenizers.whitespace,
			prefetch: source + '&prefetch&uri=' + current_uri,
			remote: {
				url: source + '&remote&uri=' + current_uri + '&q=%QUERY',
				wildcard: '%QUERY'
			}
		});

    VM6484:1 Uncaught ReferenceError: Bloodhound is not defined
