### ISSUE TITLE
Vanilla js alternative

### ISSUE THREAD

**Issue by jens1o** [corejavascript/typeahead.js#151]
Hi there,

I love using this library, but for a project I'm only allowed to use vanilla js.... Do you have any way to use this awesome library then? Or something like a alternative with vanilla js?

Regards,
Jens

**Comment by mokutsu** [comment]
hey @jens1o, just came across this issue from a while back.  It's not a complete solution, but in case you were interested in taking a stab, you could check out Day 6 in the Javascript30 wes bos series, it's also a typeahead input field, though there may be less event handling than with the entire typeahead.js dependency

**Comment by jens1o** [comment]
Thanks for that, that's helpful!

**Comment by jlbooker** [comment]
Sorry @jens1o This definitely requires jQuery. There is a pending PR that removes the jQuery dependency of the Bloodhoud component, so you might how a look at that. The core typeahead component will probably always require jQuery, though.
