### ISSUE TITLE
Autoselect option not working

### ISSUE THREAD

**Issue by corsacca** [corejavascript/typeahead.js#158]
I have `autoselect:true` in my typeahead options but pressing ENTER is not doing anything. 
```
Here are by typeahead options
groupsTypeahead.typeahead({
      autoselect: true,
      highlight: true,
    },
    {
      name: 'groups',
      source: groups,
      display: 'name'
    })
```
Am i missing something?

**Comment by JonathanSeguin** [comment]
Did you download the source and build? This feature is not currently in the built sources (dist) or in the latest stable release.

**Comment by rollermy** [comment]
@JonathanSeguin thanks. The build solution _works_.

**Comment by corsacca** [comment]
@JonathanSeguin thanks! The build solution works.

**Comment by DEKHTIARJonathan** [comment]
Do anyone knows when the next release will be ?
It is a bit problematic to have to build it and not use the cdn ;)

Thanks a lot

**Comment by JonathanSeguin** [comment]
I am also patiently waiting :)

**Comment by jlbooker** [comment]
Hey guys.. Been a bit busy. I'll try to get a new version built and released this afternoon.

**Comment by JonathanSeguin** [comment]
Thanks!

**Comment by jlbooker** [comment]
Version 1.2.0 is released. See: https://www.npmjs.com/package/corejs-typeahead

(Closing this for now. @corsacca please try this new release. We can re-open the issue if autoselect still doesn't work.)

**Comment by DEKHTIARJonathan** [comment]
@jlbooker : it is realeased on npm, unfortunately the tag release on github is not updated ...
This will cause some problem for some usages.

**Comment by jlbooker** [comment]
@DEKHTIARJonathan Sorry about that! I thought dist had already been rebuilt.

I rebuilt dist, recommitted, and push v1.2.1 (because NPM wouldn't move the tag to a new commit).

**Comment by DEKHTIARJonathan** [comment]
@jlbooker : thanks it's better now, but still : https://github.com/corejavascript/typeahead.js/blob/1.2.1/package.json
The version is 1.2.0 in the package.json file ;)

I mean I'm not bothered by this, I just let you know
