### ISSUE TITLE
Is there a difference between the original typeahead and this typeahead.bundle.min.js in the way we use it?

### ISSUE THREAD

**Issue by elieobeid7** [corejavascript/typeahead.js#168]
When I use the original typeahead, my code works when I use typeahead.bundle.min.js it does not.

```
$('#input').typeahead({
    source: function(query, result) {
        $.ajax({
            url: "common/search.php",
            data: 'query=' + query,
            dataType: "json",
            type: "POST",
            success: function(data) {
                result($.map(data, function(item) {
                    return item;
                }));
            }
        });
    }
});
```
I get back json encoded array. Everything is working beautifully using my typeahead I'm just trying to switch since it's not maintained.

**Comment by jlbooker** [comment]
@elieobeid7 What doesn't work about it? Do you have any error message on the development console inside your web browser?

**Comment by elieobeid7** [comment]
no error whatsoever, I'm trying to use

https://raw.githubusercontent.com/corejavascript/typeahead.js/master/dist/typeahead.bundle.min.js

this is what I'm currently using

https://pastebin.com/hGB0TPhg

Even twitter's bundle file isn't working. I guess my typeahead is old. I'm on fedora 26, chrome Version 62.0.3202.75 (Official Build) (64-bit)

**Comment by jlbooker** [comment]
That should be the correct bundle, and it's minified (which is why it looks so ugly in the raw pastebin text). Are you certain that jQuery is being included before you include the typeahead bundle?

**Comment by elieobeid7** [comment]
The one in pastebin is the one I've been using and it works fine. The first link is yours. 

Yes I'm sure Jquery is being loaded, everything loads in the footer. I just replace the content of the typeahead file I'm using with your code and typeahead stops working, so I'm using one file, it works when the content is the one posted on pastebin, it does not work when the content is your typeahead.

Please note that my version might not be the same as twitter's bootstrap, my file is some old version, called typeahead.js, I minified it and I called it typeahead.min.js

If I download twitter's typeahead.bundle.min.js it does not work either, I guess the `bundle` files contains code that is not working.

**Comment by jlbooker** [comment]
The `bundle.js` and `bundle.min.js` files just combine the `typeahead.js` and `bloodhound.js` files into one bundle. You should get just plain `typeahead.js` working first, then switch to the bundle and try to integrate the bloodhound features.

I'd suggest removing anything that's absolutely required from the page and then slowly adding complexity until you find the problem. Perhaps even use a local (static) dataset (see the examples) so you can remove the jQuery call. Once local data is working, then add in the remote data source.

**Comment by jlbooker** [comment]
Ohh, looking at this again.. Maybe it's the callback function to the `source` option on the second line of the code in your first post:

```
source: function(query, result) {
```
Should be:
```
source: function(query, syncResults, asyncResults) {
```
and the `success` callback from the `$.ajax` call should call the `asyncResults` function:
```
success: function(data) {
                asyncResults($.map(data, function(item) {
                    return item;
                }));
            }
```
