### ISSUE TITLE
Multiple span wrappers created around the original typeahead input when an additional typeahead input is created with jQuery

### ISSUE THREAD

**Issue by MakersAll8** [corejavascript/typeahead.js#178]
![image](https://user-images.githubusercontent.com/28055047/35289611-c797c42c-00a2-11e8-89c3-0eace4a4daac.png)

I am trying to allow users to insert as many rows of records as they wish to the database. One of the input fields in a row is a typeahead input. Each time I click the add a record button, some additional span is added to the original html code, adding white space on top of the input field, and messing up my user interface. What am I doing wrong? How do I fix it?

**Desired html:**
`<td colspan="2"><span class="twitter-typeahead" style="position: relative; display: inline-block;"><input type="text" class="typeahead form-control tt-hint" autocomplete="off" readonly="" spellcheck="false" tabindex="-1" style="position: absolute; top: 0px; left: 0px; border-color: transparent; box-shadow: none; opacity: 1; background: none 0% 0% / auto repeat scroll padding-box border-box rgb(255, 255, 255);" dir="ltr"><input type="text" class="typeahead form-control tt-input" name="newSubject[]" autocomplete="off" spellcheck="false" dir="auto" aria-activedescendant="" aria-owns="undefined_listbox" role="combobox" aria-readonly="true" aria-autocomplete="list" style="position: relative; vertical-align: top; background-color: transparent;"><span role="status" aria-live="polite" style="position: absolute; padding: 0px; border: 0px; height: 1px; width: 1px; margin-bottom: -1px; margin-right: -1px; overflow: hidden; clip: rect(0px 0px 0px 0px); white-space: nowrap;"></span><pre aria-hidden="true" style="position: absolute; visibility: hidden; white-space: pre; font-family: &quot;Open Sans&quot;, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: 400; word-spacing: 0px; letter-spacing: 0px; text-indent: 0px; text-rendering: auto; text-transform: none;"></pre><div role="listbox" class="tt-menu" aria-expanded="false" style="position: absolute; top: 100%; left: 0px; z-index: 100; display: none;"><div role="presentation" class="tt-dataset tt-dataset-subjects"></div></div></span></td>`

**Instead, each time I click add, I get a new span wrapped around my previously created typeahead input**

`<td colspan="2"><span class="twitter-typeahead" style="position: relative; display: inline-block;"><span class="twitter-typeahead" style="position: relative; display: inline-block;"><input type="text" class="typeahead form-control tt-hint" autocomplete="off" readonly="" spellcheck="false" tabindex="-1" style="position: absolute; top: 0px; left: 0px; border-color: transparent; box-shadow: none; opacity: 1; background: none 0% 0% / auto repeat scroll padding-box border-box rgb(255, 255, 255);" dir="ltr"><input type="text" class="typeahead form-control tt-hint tt-input" autocomplete="off" readonly="" spellcheck="false" tabindex="-1" style="position: relative; top: 0px; left: 0px; border-color: transparent; box-shadow: none; opacity: 1; background: none 0% 0% / auto repeat scroll padding-box border-box transparent; vertical-align: top;" dir="ltr" aria-activedescendant="" aria-owns="undefined_listbox" role="combobox" aria-readonly="true" aria-autocomplete="list"><span role="status" aria-live="polite" style="position: absolute; padding: 0px; border: 0px; height: 1px; width: 1px; margin-bottom: -1px; margin-right: -1px; overflow: hidden; clip: rect(0px 0px 0px 0px); white-space: nowrap;"></span><pre aria-hidden="true" style="position: absolute; visibility: hidden; white-space: pre; font-family: &quot;Open Sans&quot;, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: 400; word-spacing: 0px; letter-spacing: 0px; text-indent: 0px; text-rendering: auto; text-transform: none;"></pre><div role="listbox" class="tt-menu" style="position: absolute; top: 100%; left: 0px; z-index: 100; display: none;"><div role="presentation" class="tt-dataset tt-dataset-subjects"></div></div></span><span class="twitter-typeahead" style="position: relative; display: inline-block;"><input type="text" class="typeahead form-control tt-input tt-hint" autocomplete="off" spellcheck="false" dir="ltr" aria-activedescendant="" aria-owns="undefined_listbox" role="combobox" aria-readonly="true" aria-autocomplete="list" style="position: absolute; vertical-align: top; background: none 0% 0% / auto repeat scroll padding-box border-box rgba(0, 0, 0, 0); top: 0px; left: 0px; border-color: transparent; box-shadow: none; opacity: 1;" readonly="" tabindex="-1"><input type="text" class="typeahead form-control tt-input" name="newSubject[]" autocomplete="off" spellcheck="false" dir="auto" aria-activedescendant="" aria-owns="undefined_listbox" role="combobox" aria-readonly="true" aria-autocomplete="list" style="position: relative; vertical-align: top; background-color: transparent;"><span role="status" aria-live="polite" style="position: absolute; padding: 0px; border: 0px; height: 1px; width: 1px; margin-bottom: -1px; margin-right: -1px; overflow: hidden; clip: rect(0px 0px 0px 0px); white-space: nowrap;"></span><pre aria-hidden="true" style="position: absolute; visibility: hidden; white-space: pre; font-family: &quot;Open Sans&quot;, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: 400; word-spacing: 0px; letter-spacing: 0px; text-indent: 0px; text-rendering: auto; text-transform: none;"></pre><div role="listbox" class="tt-menu" aria-expanded="false" style="position: absolute; top: 100%; left: 0px; z-index: 100; display: none;"><div role="presentation" class="tt-dataset tt-dataset-subjects"></div></div></span><span role="status" aria-live="polite" style="position: absolute; padding: 0px; border: 0px; height: 1px; width: 1px; margin-bottom: -1px; margin-right: -1px; overflow: hidden; clip: rect(0px 0px 0px 0px); white-space: nowrap;"></span><pre aria-hidden="true" style="position: absolute; visibility: hidden; white-space: pre; font-family: &quot;Open Sans&quot;, Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: 400; word-spacing: 0px; letter-spacing: 0px; text-indent: 0px; text-rendering: auto; text-transform: none;"></pre><div role="listbox" class="tt-menu" aria-expanded="false" style="position: absolute; top: 100%; left: 0px; z-index: 100; display: none;"><div role="presentation" class="tt-dataset tt-dataset-subjects"></div></div></span></td>`

**I have the following jQuery code**

` $('#add').on('click', function (e) {
            e.preventDefault();
            $('#table').append('<tr><td colspan="3"></td><td colspan="2"><input type="text" class="typeahead form-control" name="newSubject[]" autocomplete="off"></td><td colspan="3"></td><td colspan="3"><button type="button" class="btn btn-danger btn-delete">Delete</button></td></tr>');
            $('.btn-delete').on('click', function (e) {
                e.preventDefault();
                $(this).closest('tr').remove();
            });

            var subjects = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('label'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                remote: {
                    url: '<?php echo base_url() ?>Student/searchSubject/%QUERY',
                    wildcard: '%QUERY'
                }
            });

            $('.typeahead').typeahead(null, {
                name: 'subjects',
                display: 'value',
                source: subjects,
                limit: 100,
                templates: {
                    empty: [
                        '<div class="empty-message">',
                        'No record found',
                        '</div>'
                    ].join('\n'),
                    suggestion: Handlebars.compile('<div><strong>{{label}}</strong></div>')
                }
            });

        });`

**My CSS file is this one:**
`.tt-dropdown-menu {
    max-height: 150px;
    overflow-y: auto;
}

.empty-message {
    padding: 5px 10px;
    text-align: center;
}
span.twitter-typeahead .tt-menu,
span.twitter-typeahead .tt-dropdown-menu {
    cursor: pointer;
    position: absolute;
    top: 100%;
    left: 0;
    z-index: 1000;
    display: none;
    float: left;
    min-width: 160px;
    padding: 5px 0;
    margin: 2px 0 0;
    list-style: none;
    font-size: 14px;
    text-align: left;
    background-color: #ffffff;
    border: 1px solid #cccccc;
    border: 1px solid rgba(0, 0, 0, 0.15);
    border-radius: 4px;
    -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
    background-clip: padding-box;
}
span.twitter-typeahead .tt-suggestion {
    display: block;
    padding: 3px 20px;
    clear: both;
    font-weight: normal;
    line-height: 1.42857143;
    color: #333333;
    white-space: nowrap;
}
span.twitter-typeahead .tt-suggestion.tt-cursor,
span.twitter-typeahead .tt-suggestion:hover,
span.twitter-typeahead .tt-suggestion:focus {
    color: #ffffff;
    text-decoration: none;
    outline: 0;
    background-color: #337ab7;
}
.input-group.input-group-lg span.twitter-typeahead .form-control {
    height: 46px;
    padding: 10px 16px;
    font-size: 18px;
    line-height: 1.3333333;
    border-radius: 6px;
}
.input-group.input-group-sm span.twitter-typeahead .form-control {
    height: 30px;
    padding: 5px 10px;
    font-size: 12px;
    line-height: 1.5;
    border-radius: 3px;
}
span.twitter-typeahead {
    width: 100%;
}
.input-group span.twitter-typeahead {
    display: block !important;
    height: 34px;
}
.input-group span.twitter-typeahead .tt-menu,
.input-group span.twitter-typeahead .tt-dropdown-menu {
    top: 32px !important;
}
.input-group span.twitter-typeahead:not(:first-child):not(:last-child) .form-control {
    border-radius: 0;
}
.input-group span.twitter-typeahead:first-child .form-control {
    border-top-left-radius: 4px;
    border-bottom-left-radius: 4px;
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}
.input-group span.twitter-typeahead:last-child .form-control {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
    border-top-right-radius: 4px;
    border-bottom-right-radius: 4px;
}
.input-group.input-group-sm span.twitter-typeahead {
    height: 30px;
}
.input-group.input-group-sm span.twitter-typeahead .tt-menu,
.input-group.input-group-sm span.twitter-typeahead .tt-dropdown-menu {
    top: 30px !important;
}
.input-group.input-group-lg span.twitter-typeahead {
    height: 46px;
}
.input-group.input-group-lg span.twitter-typeahead .tt-menu,
.input-group.input-group-lg span.twitter-typeahead .tt-dropdown-menu {
    top: 46px !important;
}`

**Comment by MakersAll8** [comment]
I think I figured out how to solve my issues. Should have done some rubber duck debugging instead of posting here. Every time I call .typehead(null, ...), a span wrapper is added to the typeahead element. I added a counter to my typeahead class as a workaround.

$('#add').on('click', function (e) {
            e.preventDefault();
            $('#manage-table').append('<tr><td colspan="3"></td><td colspan="2"><input type="text" class="typeahead-'+ i +' form-control" name="newSubject[]" autocomplete="off"></td><td colspan="3"></td><td colspan="3"><button type="button" class="btn btn-danger btn-delete">Delete</button></td></tr>');
            $('.btn-delete').on('click', function (e) {
                e.preventDefault();
                $(this).closest('tr').remove();
            });

            var subjects = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('label'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                remote: {
                    url: '<?php echo base_url() ?>Student/searchSubject/%QUERY',
                    wildcard: '%QUERY'
                }
            });

            $('.typeahead-'+i).typeahead(null, {
                name: 'subjects',
                display: 'value',
                source: subjects,
                limit: 100,
                templates: {
                    empty: [
                        '<div class="empty-message">',
                        'No record found',
                        '</div>'
                    ].join('\n'),
                    suggestion: Handlebars.compile('<div><strong>{{label}}</strong></div>')
                }
            });

            i++;

        });

**Comment by jlbooker** [comment]
Hi @MakersAll8 Yes, you are correct. Every time you call `$('.myClass').typeahead(...)`, the typeahead component will wrap the element(s) matched by `$('.myClass')` in a new `<span>` tag. This is by design. The only way to avoid the multiple span tag problem is by only calling `.typeahead(...)` once per element.
