### ISSUE TITLE
Suggestions with no user input

### ISSUE THREAD

**Issue by haoliangyu** [corejavascript/typeahead.js#193]
It would be great to have a `blankSearch` option to enable the display of the typeahead menu. If true, the suggestion menu should open when the user's focus is on the input box, even with no input yet. This will be helpful to show initial suggestions/recommendations.

**Comment by ymek** [comment]
This functionality already exists and is documented here: https://typeahead.js.org/examples/#default-suggestions

**Comment by haoliangyu** [comment]
Thanks for helping!
