### ISSUE TITLE
"Is not a function" when work with Webpack Encore

### ISSUE THREAD

**Issue by vezuwio** [corejavascript/typeahead.js#200]
Hi, maybe someone try to use this pack with symfony and webpack encore bundle?
I tried and when I installed it using Yarn and imports in specified file:

import 'corejs-typeahead/dist/bloodhound.min.js';
import 'corejs-typeahead/dist/typeahead.bundle.min.js';
import 'corejs-typeahead/dist/typeahead.jquery.min.js';

I get an error "TypeError: $(...).typeahead is not a function".

Any ideas?

I use cdn and everythink work correctly but it's not the best solution and I must use webpack.

Thank you for any help ;)

When I use pack from cdn

**Comment by simplenotezy** [comment]
I get this as well, but not with typeahead. I get `Uncaught ReferenceError: Bloodhound is not defined`

**Comment by pszalko** [comment]
I have the same issue. Did you resolve it on your own @vezuwio ?

**Comment by jlbooker** [comment]
See #221. Typeahead.js is not a module, so you can't just "import" it. Include it in its own `<script>` tag after jQuery.
