### ISSUE TITLE
Version numbers don't match

### ISSUE THREAD

**Issue by dregad** [corejavascript/typeahead.js#201]
According to https://github.com/corejavascript/typeahead.js/releases, the latest version is 1.2.1, but the corresponding [files in dist/ directory](https://github.com/corejavascript/typeahead.js/tree/1.2.1/dist) indicate they are 1.2.0.

Same problem with 1.2.0 dist files, they report being 1.1.1

Not a huge deal, but confusing at first - if you could fix that it would be great.

**Comment by jlbooker** [comment]
Ahh, good catch. I thought those were auto-generated by the release process, but apparently not. I'll see about merging anything I (easily) merge this morning and rolling another release.

**Comment by jlbooker** [comment]
I see what happened. I tagged version 1.2.0, but something happened with the `npm publish` and I had to bump the package up to v1.2.1 to get NPM to accept it. I didn't rebuild the project after I did that, though -- I just updated package.json and re-published.

Anyhow, 1.3.0 is out now, so everything should match again.

**Comment by dregad** [comment]
Cheers !

**Comment by dregad** [comment]
@jlbooker Sorry, but there is one more thing left to do to fully fix this... You did not tag the 1.3.0 release, so it (and the updated dist files) don't show up on CDN (https://cdnjs.com/libraries/corejs-typeahead).

**Comment by dregad** [comment]
Any chance you could tag the 1.3.0 release this week ?

**Comment by jlbooker** [comment]
Tagged! https://github.com/corejavascript/typeahead.js/tree/v1.3.0

**Comment by dregad** [comment]
Awesome, thanks !
