### ISSUE TITLE
Applying typeahead breaks a properly-styled Bootstrap 3 text input form

### ISSUE THREAD

**Issue by iandees** [corejavascript/typeahead.js#215]
When typeahead.js is applied to a properly-styled Bootstrap 3 form, the styling becomes broken and the typeahead dropdown becomes invisible:

<img width="603" alt="image" src="https://user-images.githubusercontent.com/261584/74952676-34a3c700-53c6-11ea-9917-41f34af4f271.png">

The screenshot is from this jsfiddle, where the two forms are identical HTML but the top text field has typeahead.js applied and the bottom doesn't.

https://jsfiddle.net/d25h8mcj/2/

I believe [this library](https://github.com/bassjobsen/Bootstrap-3-Typeahead) could be used to fix the styling, but it doesn't seem to work with corejs-typeahead.

**Comment by erisilva** [comment]
I use this css:
`<style>
  .twitter-typeahead, .tt-hint, .tt-input, .tt-menu { width: 100%; }
  .tt-query, .tt-hint { outline: none;}
  .tt-query { box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);}
  .tt-hint {color: #999;}
  .tt-menu { 
      width: 100%;
      margin-top: 12px;
      padding: 8px 0;
      background-color: #fff;
      border: 1px solid #ccc;
      border: 1px solid rgba(0, 0, 0, 0.2);
      border-radius: 8px;
      box-shadow: 0 5px 10px rgba(0,0,0,.2);
  }
  .tt-suggestion { padding: 3px 20px; }
  .tt-suggestion.tt-is-under-cursor { color: #fff; }
  .tt-suggestion p { margin: 0;}
</style>`

**Comment by iandees** [comment]
Thanks, that seems to help!

https://jsfiddle.net/gdkcwexq/3/

**Comment by sokollondon** [comment]
**Bootstrap 3**
https://github.com/bassjobsen/typeahead.js-bootstrap-css/blob/master/typeaheadjs.css

**Bootstrap 4**
https://github.com/bassjobsen/typeahead.js-bootstrap4-css/blob/master/typeaheadjs.css
