### ISSUE TITLE
typeahead suggestions list not decreasing

### ISSUE THREAD

**Issue by soxy95** [corejavascript/typeahead.js#218]
Hello, 

I've very long json list around 31000 lines
My json looks like that
<pre>[
  {
    "CODE_INSEE": 1344,
    "DESIGNATION": "1000 SAINT-DENIS-LES-BOURG"
  },
  {
    "CODE_INSEE": 1053,
    "DESIGNATION": "1000 BOURG-EN-BRESSE"
  },
  {
    "CODE_INSEE": 1225,
    "DESIGNATION": "1090 LURCY"
  },
  {
    "CODE_INSEE": 1165,
    "DESIGNATION": "1090 FRANCHELEINS"
  },
  {
    "CODE_INSEE": 1263,
    "DESIGNATION": "1090 MONTMERLE-SUR-SAONE"
  },
  {
    "CODE_INSEE": 1169,
    "DESIGNATION": "1090 GENOUILLEUX"
  }
]
</pre>
The suggestions list never decrease, i still have the first ten items of the json list.

<pre>$(document).ready(function($) {
var cities_suggestions = new Bloodhound({
datumTokenizer: Bloodhound.tokenizers.obj.whitespace("DESIGNATION"),
queryTokenizer: Bloodhound.tokenizers.whitespace,
remote: {
      url: "villes2.json",
      transform: function(data) {
        var newData = [];
        data.forEach(function(item) {
          newData.push(item.DESIGNATION);
        });
        console.log(newData);
        return newData;
      }
    }
  });
  cities_suggestions.initialize();
  $("#my_search").typeahead(
    {
      hint: true,
      minLength: 1,
      highlight: true
    },
    {
      name: "cities",
      source: cities_suggestions, // suggestion engine is passed as the source
      limit: 10
    }
  );
})</pre>

In the console.log(newData), i have correct list of city but it's not enought bescause i need CODE_INSEE too... but it's not my priority.
So I'im trying to have

- suggest city to the internaut 

- Fill hidden input type="text" with the "CODE_INSEE"

![bureau](https://user-images.githubusercontent.com/62827885/77843172-eb038480-719a-11ea-87b4-11a593f5d9ab.png)

**Comment by keywan-ghadami-oxid** [comment]
Looks to me like you using it in the wrong way. The remote setting should be used for a server side search but I gess
 url: "villes2.json" 
points to a static file.
If you want to use a in browser search only you can achieve that with the 'local' setting.
