### ISSUE TITLE
Typeahead and Webpack error: $(...).typeahead is not a function

### ISSUE THREAD

**Issue by guilpejon** [corejavascript/typeahead.js#221]
Hello, everyone!

My issue is related to this one: https://github.com/twitter/typeahead.js/issues/1627.

I'm trying to use `typeahead.js` in a personal Ruby on Rails project but it's been a few days now and I still haven't solved this issue. I can import and use `Bloodhound` without a problem, but I keep getting the `typeahead is not a function` error. I tried almost everything, including all the suggestions in the issue I mentioned above, but nothing worked.

I created the simplest Rails application ever to reproduce the problem. Here it is: https://github.com/guilpejon/typeahead-bug

Does anyone have any idea on how to solve this?

Thanks in advance!

**Comment by JackSlaterIV** [comment]
I have the same issue using Webpack.
Did you find any solution?

**Comment by jlbooker** [comment]
@guilpejon Do you have that project hosted anywhere? I'd need to see the actual HTML+JS for the page this error is happening on. Are you bundling the JS with Webpack or some other tool?

**Comment by JackSlaterIV** [comment]
Update: in Webpack I got it working like this:
```
global.$ = require('jquery');
global.Bloodhound = require('corejs-typeahead/dist/bloodhound.js');
require('corejs-typeahead/dist/typeahead.jquery.js');
```
I hope it helps.

@jlbooker 
Is there a place here where I can ask a question about this library?

**Comment by reedids** [comment]
I did like this in webpack, import way.

- "corejs-typeahead": "^1.3.1",
- "webpack": "^4.18.0",

```js
// in entry js file
import Bloodhound from 'corejs-typeahead/dist/bloodhound.js';
import 'corejs-typeahead/dist/typeahead.jquery.js';
```

```js
// webpack.config.js
plugins: [
  new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery',
    ... 
  }),
],
```

**Comment by jlbooker** [comment]
I'm going to close this for inactivity and since it's related to bundling with Webpack and not directly a bug/feature in Typeahead.
