### ISSUE TITLE
Callback not being called when typing

### ISSUE THREAD

**Issue by senechalm** [corejavascript/typeahead.js#223]
trying to implement the typeahead search in nodejs with mysql, but looks like there is a bug:

When manually going to http://127.0.0.1:5000/search?key=s for example, I can see the result and my debug logs in the console. 
But when typing in the input text, it's not showing anything nor can't see the console.log("debug") in the console so looks like the /search is not even called

here is the index.html: 
<!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>test</title>
        <script src="https://code.jquery.com/jquery-latest.js"></script>
        <script src="https://cdn.rawgit.com/corejavascript/typeahead.js/master/dist/typeahead.jquery.js"></script>
        
    </head>

    <body>
        <input class="typeahead tt-query" spellcheck="false" autocomplete="off" name="typeahead" type="text" />
        <script type="text/javascript">
            $(document).ready(function(){
                $('input.typeahead').typeahead({
                    name: 'Name',
                    remote: 'http://127.0.0.1:5000/search?key=%QUERY',
                    limit: 10
                });
            });
        </script>
    </body>
    </html>

and the App.js:

````
const express = require('express');
const fileUpload = require('express-fileupload');
const bodyParser = require('body-parser');
const mysql = require('mysql');
const path = require('path');
const app = express();

const {getHomePage} = require('./routes/index');
const port = 5000;

// create connection to database
// the mysql.createConnection function takes in a configuration object which contains host, user, password and the database name.
const db = mysql.createConnection ({
    host: 'localhost',
    user: 'raid',
    password: 'raid',
    database: 'raid',
    port: 3308
});

// connect to database
db.connect((err) => {
    if (err) {
        throw err;
    }
    console.log('Connected to database');
});
global.db = db;



// configure middleware
app.use(express.static(__dirname + '/public'));
app.set('port', process.env.port || port); // set express to use this port
app.set('views', __dirname + '/views'); // set express to look in this folder to render our view
app.set('view engine', 'ejs'); // configure template engine
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json()); // parse form data client
app.use(express.static(path.join(__dirname, 'public'))); // configure express to use public folder
app.use(fileUpload()); // configure fileupload

app.engine('html', require('ejs').renderFile)
// routes for the app

app.get('/raid', function(req, res){
    res.render('index.html');
})

app.get('/search', function(req, res){
    console.log("debug")
    db.query('SELECT Name from champions where Name like "%'+req.query.key+'%"',
    function(err, rows, fields) {
    if (err) throw err;
    var data=[];
    for(i=0;i<rows.length;i++)
    {
    data.push(rows[i].Name);
    }
    res.end(JSON.stringify(data));
    });
    });

app.get('/', getHomePage);


// set the app to listen on the port
app.listen(port, () => {
    console.log(`Server running on port: ${port}`);
});

**Comment by jlbooker** [comment]
You'll need to take the console.log calls out of the node application. They will likely cause the json output to be invalid.

The cause of the issue I see is in this section:
```
<script type="text/javascript">
        $(document).ready(function(){
            $('input.typeahead').typeahead({
                name: 'Name',
                remote: 'http://127.0.0.1:5000/search?key=%QUERY',
                limit: 10
            });
        });
    </script>
```

Typeahead doesn't have a `remote` option (the Bloodhound package does). Typeahead uses a `source` options that expects a callback function. See docs here: https://github.com/corejavascript/typeahead.js/blob/master/doc/jquery_typeahead.md#datasets

I think you want to use something like Bloodhound and follow this example: https://typeahead.js.org/examples/#remote
In that example, note that `bestPictures` is a reference to a Bloodhound object, and that Bloodhound object was created with a `remote:` key.

**Comment by senechalm** [comment]
got you so I tried this example and got this error:
Uncaught ReferenceError: Bloodhound is not defined

I'm using typeahead.bundle.js v0.11.1 : 
/*!
 * typeahead.js 0.11.1
 * https://github.com/twitter/typeahead.js
 * Copyright 2013-2015 Twitter, Inc. and other contributors; Licensed MIT
 */

**Comment by jlbooker** [comment]
Be sure you include Bloodhound (for the previous 'Bloodhound is undefined' error). You probably want to include this file instead, as it bundles both Typeahead and Bloodhound together:
```
<script src="https://cdn.rawgit.com/corejavascript/typeahead.js/master/dist/typeahead.bundle.js"></script>
```

You probably need to change the jQuery selector from the example code:
`$('#remote .typeahead').typeahead( [...]`

That line matches a specific element in the example HTML. It probably won't match the element in your HTML. In your first example you were using `$('input.typeahead')`

**Comment by senechalm** [comment]
Hi, thanks for your answer, however I still have the same issue,
I did include the right librairies
and for the JQuery selector, sorry I haven't put the whole code but I changed it to be the exact same as the example

`<!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>test</title>
        <script src="https://code.jquery.com/jquery-latest.js"></script>
        <script src="https://twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
        
    </head>

    <body>
        <div id="remote">
            <input class="typeahead" type="text" placeholder="Oscar winners for Best Picture">
          </div>
        <script type="text/javascript">
            $(document).ready(function(){
                var Name = new Bloodhound({
                    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
                    queryTokenizer: Bloodhound.tokenizers.whitespace,
                    remote: {
                        url: 'http://localhost:5000/search?key=',
                        wildcard: '%QUERY'
                    }
                    });

                    $('#remote .typeahead').typeahead(null, {
                    name: 'c-Name',
                    display: 'value',
                    source: Name
                });
            });
        </script>
    </body>
    </html>
`

Still having the same behaviour : no errors but nothing is happening either

**Comment by jlbooker** [comment]
Have a look in your browser's developer tools, in the "Network" tab, and see if any requests are being sent. It may be that the query is incorrect, or that the backend isn't returning the results as expected.

**Comment by senechalm** [comment]
Hi,

Thank you very much for your help on that
I did check the console and you're right I can see the query and the response. the result is correct, but still nothing is displayed nor the result nor the dropdown (see screenshoot here : 
![image](https://user-images.githubusercontent.com/6816808/85308881-b5282080-b4a9-11ea-93cb-7a1a9170ea3b.png)

**Comment by jlbooker** [comment]
I think you need to remove the `display: 'value',` line.

You would only use this line if your JSON result set is an array of objects. The name `value` would be the key name in the array to use for the suggestion. For example: 
`[{id: 1,value:"Valerie"},{id:2,value:"Chevalier Cerf"}]`

Your JSON response is *not* using this format, so you don't need the `display` parameter.

**Comment by senechalm** [comment]
Hi,
thanks very much for your support, I now fixed the issue thanks to your help:
1. Changed the backend to return the Name and ID : `[{id: 1,Name:"Valerie"},{id:2,Name:"Chevalier Cerf"}]`
2. on the frontend, I'm using the Name for displaying purpose, but keep the ID to do other stuff

This can be closed

**Comment by jlbooker** [comment]
Glad to hear you have it working!
