### ISSUE TITLE
Any document around the implementation of bloodhound

### ISSUE THREAD

**Issue by pruthvip** [corejavascript/typeahead.js#232]
Is there any documentation/blog/video talk etc explaining the inner working/implementation of bloodhound. Or should we read through the code?

**Comment by jlbooker** [comment]
Unfortunately, no. It was mostly written by Jake Harding. He worked for Twitter at the time. Other than the documentation in the Readme files here, you'll have to dig into the source code. This is the best docs that exist on Bloodhound.js:
https://github.com/corejavascript/typeahead.js/blob/master/doc/bloodhound.md
