### ISSUE TITLE
Offset option is not working

### ISSUE THREAD

**Issue by GlennSchniedes** [corejavascript/typeahead.js#234]
I'm using Typeahead for a long time, but as of today I want to use the option 'offset'. So that the autocomplete shows the values, starting with the input (referring to the typeahead documentation). But I can't let it work, I cleared the cache. Tried multiple times, but I can't let it work.

`$('#registration').typeahead({
          hint: false,
          highlight: true,
          minLength: 1,
          order: "asc",
          offset: true,
          cache: false
},
{
          name: 'registrationSearch',
          display: 'registration',
          limit: 5,
          source: registrationsMultiply
        });`

Via the link you see a screenshot, how the autocomplete looks like (live in action): https://ibb.co/bL3YT5M

**Comment by jlbooker** [comment]
I don't see an `offset` option listed in either of the docs:
https://github.com/corejavascript/typeahead.js/blob/master/doc/jquery_typeahead.md
https://github.com/corejavascript/typeahead.js/blob/master/doc/bloodhound.md

What typeahead documentation were you referring to?

**Comment by 7521TwebstarH10878** [comment]
Simply pull the end denotion value to flow in statement that make value true in language free flow no blocks like the flow . Tim Harvath
