### ISSUE TITLE
Use with ES6 import

### ISSUE THREAD

**Issue by augnustin** [corejavascript/typeahead.js#236]
I can't make it work with ES6 imports. :disappointed: 

I tried:

```
import $ from 'jquery';

import 'corejs-typeahead';
// or this
import 'corejs-typeahead/dist/typeahead.jquery.js';
// or this
import anything from 'corejs-typeahead/dist/typeahead.bundle.js';
```
But with `$('#search_query').typeahead()`, I get: 

```
searchbar.js:11 Uncaught TypeError: jquery__WEBPACK_IMPORTED_MODULE_0___default(...)(...).typeahead is not a function
```
Help appreciated.  Thanks

**Comment by jlbooker** [comment]
This jQuery plugin isn't bundled as an es6 module. It doesn't export anything, so I'd be very surprised if you can import from it directly. You may be able to wrap it in an es6 module format, but it isn't distributed that way.

Try using a script tag:
```
<script type="text/javascript" src="jquery.js">
<script type="text/javascript" src="corejs-typeahead/dist/typeahead.bundle.js">
```

**Comment by augnustin** [comment]
Weird that the so-called "maintained version" is not ES6 compatible. :open_mouth: 

> I'd be very surprised if you can import from it directly.

Since jQuery plugins are about extending the `jQuery` object, it should be possible to make it export a function that takes `$` as an argument and returns the updated version. But anyway, the issue is closed, so no need to go further...

I did make my own wrapped version.

**Comment by jlbooker** [comment]
Bruh, this project dates back to 2013. Before ES6, CommonJS, and Webpack/bundlers were things. This project is "maintained" in the sense that bugs and minor feature patches are accepted and occasionally released. What you want is a major feature request to repackage this and ship it as a proper ES6 module. That would be a major compatibility break from the way this project has been intended to be used. I don't see anyone jumping on that project, given the decline in popularity of jQuery and associated plugins. This project is probably stuck in pre-bundler times, but it is kept alive at a minimal level.
