### ISSUE TITLE
Esc key propagates after closing menu

### ISSUE THREAD

**Issue by jacobbroberg** [corejavascript/typeahead.js#24]
I use the typeahead (latest build, 9c2b65cb107b5a479230b238278ffdb83fae6161) in a modal dialog. When I click the `Esc` key the typeahead menu closes, but my modal dialog also closes (because it is set to close when `Esc` is clicked.

Since this issue is very similar to the one solved in #13 (which solves the same propagation problem when selecting an entry with the `Enter` key), I tried implementing the same for the `Esc` key, by adding `$e.preventDefault()` and `$e.stopPropgation()` in `_onEscKeyed()` (see d0371ed3d37e0be736305303277caccd63761d4c). However, this is not enough since my modal dialog binds to the `keyUp` event and typeahead only listens for `keyDown`. 

Any ideas on how this should be solved. In order to truly prevent an `Esc` key click to propagate, I do believe typeahead should stop propagation for both `keyDown` and `keyUp`. Could a solution be to call  `close()` on `keyUp` instead and simply suppress `keyDown` - as long as the menu is open of course?

**Comment by jacobbroberg** [comment]
Would anyone think it was a good idea if I tried making a pull request for stopping propagation and/or preventing default for the `keyUp` and `keyDown` events used by the typeahead (like in #13)? I was since this was written had similar problems with down and up keys propagating out of the typeahead.

**Comment by sheeley** [comment]
I'd support that as an option!
