### ISSUE TITLE
Can't replicate remote example with Django supplying JSON / don't know how to debug

### ISSUE THREAD

**Issue by chrisjdixon** [corejavascript/typeahead.js#246]
[Asked over at SO](https://stackoverflow.com/questions/68920637/supplying-remote-json-data-for-typeahead-bloodhound-with-django-python): I'm having trouble replicating [the remote example](http://twitter.github.io/typeahead.js/examples/#remote) and can't figure out what I'm doing wrong.

[The JSON retrieved by that example for "kings" shows the format it's being received](https://twitter.github.io/typeahead.js/data/films/queries/kings.json):
```json
[
  {
    "year": "1949",
    "value": "All the Kings Men",
    "tokens": [
      "All",
      "the",
      "Kings",
      "Men"
    ]
  }
]
```
which differs to how I've supplied it with Django / Python:
```py
nouns = ['apple', 'banana', 'pear']
return JsonResponse({'value': nouns})
```
which arrives as `{"value": ["apple", "banana", "pear"]}`. Need it be of the example's same specific format? If so, how could I do that?

My code for Typeahead / Bloodhound:
```html
<div class="col-12">
  <div id="the-basics">
    <input class="typeahead form-control" id='typeahead' type="text">
  </div>
</div>
```
```js
var egDjangoVar = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  remote: {
    url: '/ajax/eg/%QUERY.json', 
    wildcard: '%QUERY'
  }
});

$('#the-basics .typeahead').typeahead(null,
{ 
  name: 'results',
  display: 'value',
  source: egDjangoVar
});
```
What am I doing wrong?

Sorry if this is a dumb question but I'm new to front end and I'm at my wits end here. Feel free to redirect me elsewhere.

**Comment by chrisjdixon** [comment]
[Figured it out](https://stackoverflow.com/a/68939755/4107349) for practical use `return HttpResponse(nouns)`, or `return JsonResponse(nouns, safe=False)`.

If concerned for security send it as a dict:
```js
noun_dicts = [{'suggestion':x} for x in nouns]
return JsonResponse({'results':noun_dicts})
```
And then parse the dict in JS.

**Comment by jlbooker** [comment]
Hi @chrisjdixon, Sorry I didn't see this in time to help you out. Glad you got it resolved though.
