### ISSUE TITLE
New release to npm?

### ISSUE THREAD

**Issue by exortech** [corejavascript/typeahead.js#255]
Any chance of deploying a new release to npm? It looks like 1.3.2 was not published to npm. I'd love to pull down the accessibility improvements that have been made. Could this be packaged into a 1.3.3 release?

**Comment by exortech** [comment]
Thanks! 🙌

**Comment by jlbooker** [comment]
@exortech Sorry it took a little longer than I hoped, but v1.3.3 is published: https://www.npmjs.com/package/corejs-typeahead/v/1.3.3

**Comment by exortech** [comment]
Thanks for making the release @jlbooker . However, it doesn't look like the files in the dist folder have been updated: https://github.com/corejavascript/typeahead.js/tree/master/dist. They still show as version 1.3.1. These files enable us to pull the scripts from npm without needing to build them.

**Comment by p-bakker** [comment]
Also, while there are tags in git for the 1.3.2 and 1.3.3 release, they aren't marked here in gitHub as releases, so gitHub shows 1.3.0 as the last release, which is a bit confusing...

Would also be nice if there were some release notes with each release :-)

**Comment by jlbooker** [comment]
> Would also be nice if there were some release notes with each release :-)

See https://github.com/corejavascript/typeahead.js/blob/v1.3.4/changelog.md

**Comment by jlbooker** [comment]
I've just rebuild the dist file, committed those, and tagged/released v1.3.4 on both GitHub and NPM. @exortech, Please give this version a try and report back. (Apologies for the year-long delay!)

**Comment by exortech** [comment]
Thanks @jlbooker ! I've integrated the new version. One minor thing: the version showing in the file header comments for the built files in the /dist folder still show as 1.3.3. So it's a point release behind.

The accessibility fix didn't address the issue that I was seeing - namely that the generated input element was missing a label. But I was able to address it by adding an aria-labelledby element to the input that it replaces.

**Comment by jlbooker** [comment]
Ahh yea.. I think the build scripts use the version number from the package.json file, but I ran the build before I incremented the version number, so they picked up the old version... I'm not too worried about that not matching. I'll mark this as closed for now. Please feel free to submit a PR for the accessibility fix you made!
