### ISSUE TITLE
Triggering and Scoping typeahead with symbol (@, # ...)

### ISSUE THREAD

**Issue by duranmla** [corejavascript/typeahead.js#29]
Hi, I saw that this suppose to be the right place to discuss about typeahead. Recently I start to work with this in my meteor app, I'd posted this question into the [meteor-typeahead project](https://github.com/sergeyt/meteor-typeahead/) too. What I want to know (or do, if it is possible) is if there is a way to set like: "only fetch results after type X symbol" in addition it would be more powerful if we have a way to scope the source using the trigger symbol like:

Bring me the tags after type #
Bring me the users after type @

If there is a way could someone throw me a link here? or a simple example. Otherwise, I will be more than happy to help to do so.

**Comment by marcel-k** [comment]
Is this wat your searching for? http://sandglaz.github.io/bootstrap-tagautocomplete/

**Comment by jlbooker** [comment]
I don't think there's currently a way to do what you're looking for (requesting the search results only after some "trigger" character is typed). I'm closing this due to age/inactivity. If you're still interested in this as a feature request, please comment and we'll reopen.
