### ISSUE TITLE
No results found in Mozilla Firefox

### ISSUE THREAD

**Issue by vedroide2e4** [corejavascript/typeahead.js#31]
Hello,

I use typeahead.js version '0.11.1'. for two depended input fields like "street" and "building". 

When we got the value of field "street"  then we can make a query for filed "building". It works fine in all browsers, even in mobile. But not in Mozilla Firefox (in adnroid version too). In firefox there is no action in field "building" after we made choose in field "street". But, if we try in second (third,....) time then it works...until next page update.

I founded the way to fix it, but I think it's not the right way.

Sorry for my english ;-)

Problem part of code looks like:

``` javascript
var updateStates = function () {
    var streetValue = currentStreet; //Doesn't work in Firefox without this line
    var streetValue = streetInput.val (); //Works fine in all other browsers
    var buildingValue = buildingInput.val ();
    var badStreet = streetValue.replace (/\s/g, '').length < STREET_MIN;
    if (badStreet || buildingValue.replace (/\s/g, '').length < BUILDING_MIN || (streetValue == lastStreetName && buildingValue == lastBuildingName)) {
      btnDisabled = true;
      searchButton.attr ('disabled', 'disabled');
    } else {
      btnDisabled = false;
      searchButton.removeAttr ('disabled');
    }
    if (badStreet)
      setDisabled (buildingInput, true);
    else
      setDisabled (buildingInput, false);
  };
```

And here we got the problem function

``` javascript
streetInput
    .typeahead (null, conf ('street', 'ajax.php?load=streets&query=%QUERY'))
    .on ('typeahead:select', function (event, street) {
      setStreet (street); //Doesn't work for first time on page load in Firefox
      buildingInput[0].focus ();
    }).on ('change keyup', function () {
      if (currentStreet)
        setStreet (null);
      else
        updateStates ();
      setupBuildingAutocomplete ('street_name=' + urlencode ($(this).val ()));
    }).on ('keydown', keydown);
```

**Comment by sheeley** [comment]
Hi - taking a look at your example, there are a number of pieces that prevent us from reproducing. Could you try paring it down (take a look at http://stackoverflow.com/help/mcve)? For example, I don't know what `setStreet`, `keydown`, or `setupBuildingAutocomplete` do - I assume they don't impact this scenario and so removing them will make it simpler to debug.

**Comment by jlbooker** [comment]
Closing to due age/inactivity. Please comment if you're still encountering this bug and we'll reopen the issue.
