### ISSUE TITLE
Simple use of this library! not really as simple as the 0.9.3

### ISSUE THREAD

**Issue by zenithtekla** [corejavascript/typeahead.js#35]
Hello,
I know yours is a forked version. However, May I raise my concern over complexity that stacks up and may deter simplicity concern (simplicity of use)?

Here is my original text:
https://github.com/twitter/typeahead.js/issues/1425

I ran through this link http://code.runnable.com/UlXgeluakNULAAAv/create-an-autocomplete-input-box-with-typeahead-js-for-jquery-and-javascript and found out that the old version takes less to perform a simple task, without having to use Bloodhound. But maybe in this forked Typeahead, you already fixed it?

I'm using Bloodhound as much as I use Typeahead, so I am not afraid of having to use it but it's just my constructive query. Your input is appreciated.
Regards,

**Comment by jcrben** [comment]
This fork is new and not much different from its parent.

I agree that the library now feels a bit overengineered, at least to me, and this is a really common complaint. But that's not an easy fix. Have you tried downloading the prior version?

**Comment by zenithtekla** [comment]
I opened another thread regarding to the Trie data structure issue. Can you have a look?
