### ISSUE TITLE
Detach fork into own repository

### ISSUE THREAD

**Issue by karlhorky** [corejavascript/typeahead.js#38]
Since the original repository is no longer being maintained, I would suggest separating this into its own repository along with working bower and npm packages.

As to how to do it, GitHub [says to contact support](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork):

> To detach the fork and turn it into a standalone repository on GitHub, contact [GitHub support](https://github.com/contact).

**Comment by karlhorky** [comment]
This is what I got when I tried installing the bower package:

```bash
$ bower install --save corejs-typeahead
bower                        ENOTFOUND Package corejs-typeahead not found
```

**Comment by amenadiel** [comment]
to my knowledge, at this point there's no bower nor npm url, at least until the next release/tag.

But you can just clone this repo for the time being.

**Comment by sheeley** [comment]
Correct, I believe the gameplan is to get tests working again and then release - it does seem to make sense to detach, as forks are not searchable. What do you think, @corejavascript/collaborators?

**Comment by flirtomania** [comment]
http://forked.yannick.io/
I found this fork with that thing. I think it makes sense to remain it as fork, so people could find it.

**Comment by sheeley** [comment]
Good to know, thanks!

**Comment by karlhorky** [comment]
I would say the benefits of separating into its own repo outweigh the drawbacks. Along with the separation, a pull request can be opened on the main repository to point to the new project in the readme, making discovery of this project easier.

**Comment by willthemoor** [comment]
I agree. I didn't realize until I just searched for [nonword](https://github.com/corejavascript/typeahead.js/search?q=nonword&type=Code&utf8=%E2%9C%93) that forks can not be searched.

> Sorry, forked repositories are not currently searchable.
> You could try searching the parent repository.

**Comment by jlbooker** [comment]
I've sent a request to GitHub support to have this repo detached from the parent.

**Comment by jlbooker** [comment]
Thanks to @lenovouser for approving, and GitHub support for their help, this is now complete.

**Comment by karlhorky** [comment]
Great, thanks @jlbooker!
