### ISSUE TITLE
Limit does not work properly

### ISSUE THREAD

**Issue by mlissner** [corejavascript/typeahead.js#43]
Using typeahead 0.11.1.

I have a remote endpoint that always returns 0-20 results. I don't use prefetch and I don't use local. I'm not using bloodhound, so there's no filtering or caching going on there. Nevertheless, I get really strange numbers of results from typeahead:

 - `limit: 19`: Seems to work most of the time, but sometimes it returns only the first two results.
 - `limit: 20`: lots of queries don't give me any results. I believe this is due to the number of results being equal to `limit`, as in issue #30.
 - `limit: 30`: I get ten results, even when my remote returned 20. No clue why.

I honestly don't know what's going on with it at this point, but messing around with limit makes my result count change in all kinds of weird ways.

**Comment by mwjackson** [comment]
This may be the issue

https://github.com/twitter/typeahead.js/issues/1435

**Comment by mlissner** [comment]
Could be, but the code seems pretty different from what is in that bug report, and I don't pretend to understand what it's supposed to be doing. 

Here's what I *think* is the current code:
```javascript
                function async(suggestions) {
                    suggestions = suggestions || [];
                    if (!canceled && rendered < that.limit) {
                        that.cancel = $.noop;
                        that._append(query, suggestions.slice(0, that.limit - rendered));
                        rendered += suggestions.length;
                        that.async && that.trigger("asyncReceived", query);
                    }
                }
```

In the bug it refers to code that should be:

    var idx = (that.limit > rendered) ? rendered : that.limit;
    that._append(query, suggestions.slice(0, idx));

Would love a fix for this. It's a pretty wonky problem.

**Comment by mwjackson** [comment]
replace that._append with the two lines suggested and that fixed it for me.

**Comment by mlissner** [comment]
Thanks @mwjackson. I tried that, but when I put those two lines in place, I couldn't get back any results at all, no matter how many results the backend returned.

**Comment by mwjackson** [comment]
This is how my async function looks:

                function async(suggestions) {
                    suggestions = suggestions || [];
                    if (!canceled && rendered < that.limit) {
                        that.cancel = $.noop;
                        rendered += suggestions.length;
                        var idx = (that.limit > rendered) ? rendered : that.limit;
                        that._append(query, suggestions.slice(0, idx));
                        that.async && that.trigger("asyncReceived", query);
                    }
                }

**Comment by mlissner** [comment]
Yes! That fixed it! What should we do to get this change checked in? Are you a committer?

**Comment by mwjackson** [comment]
No... just commit it to a branch and submit a PR

**Comment by jcrben** [comment]
@mwjackson do you want to be a committer?

@lenovouser is the owner and seems open to giving people privileges

**Comment by mlissner** [comment]
OK, Pull Request created. I'm hopeful we can get this released quickly. It's a pretty major issue unless I'm mistaken.

**Comment by mlissner** [comment]
This has been merged! Closing.

**Comment by jlbooker** [comment]
Tracking this for release soon, see #55
