### ISSUE TITLE
Why this needs to run bower after npm install?

### ISSUE THREAD

**Issue by rafaellyra** [corejavascript/typeahead.js#47]
I was trying to use this fork instead of the twitter/typeahead.js but this is running a bower install after the npm install, I don't have bower in my CI and I do think that it shouldn't be a dependency when installing with npm. I noticed that bower is just installing jQuery and Jasmine and I think that Jasmine should be a devDependencie and jQuery can be installed as NPM dependency. If you guys agree with that I can open a PR with the changes.

**Comment by DanielApt** [comment]
I agree, using bower to instal deps seems like a rarity nowadays.

**Comment by jcrben** [comment]
Only npm 3 uses a flattened directories, and it is *very* recent. That's why bower is useful. Plus the npm ecosystem is a messy mix of nodejs and browser-targeted packages. This isn't a node project.

Last I looked at npm it wasn't recommended for production use. Is it all smoothed out now?

**Comment by rosskevin** [comment]
@jcrben - npm is a package manager, and bower is a package manager.  I'm not sure what concerns there are about production use, but any package manager has to be used with production control in mind, andI don't see how npm could weaker than bower.

npm isn't just for node any more, it's free standing and every package I've wanted is available there.  Is bootstrap a node project?  

I recently reviewed our bower vs npm approach, and quite simply it appears to me that npm is becoming the defacto standard.  For anything where I used bower, I had to have npm.  In fact, bower is an npm package, so why am I using bower again?

I don't like swimming upstream, so out with bower and in with npm.  I'm switching our apps to npm only, while keeping our libs compatible with both, but basing the lib dependencies and toolchain on npm.  I do recommend that approach here, and if @rafaellyra is volunteering I think it's a plus to take him up on it.

**Comment by rosskevin** [comment]
Oh yes, forgot to mention, the ES6/ES2015 crowd is blazing new paths, and almost all of these support npm first, some with no bower, some with bower.

**Comment by rosskevin** [comment]
Another switch to npm: 

https://github.com/brunch/brunch/issues/633#issuecomment-180945113

**Comment by jcrben** [comment]
@rosskevin the npm changelogs had in very big bold letters that npm 3 was beta for a while so that you shouldn't rely on it for production systems, but that ended in September 2015 https://allmychanges.com/p/nodejs/npm/#3.3.4 - so yeah, theoretically it's not beta any longer and using it exclusively is not a bad idea. But you certainly should never use npm 2 for the web.

When I said npm is a mix of a node and front-end packages, I just meant that when using npm, it is possible to accidentally install and try to use packages which cannot be used for the web which can be a bit confusing.

**Comment by rosskevin** [comment]
@jcrben so it seems like we have all the information we need for a decision.  Is it a yes or no?

**Comment by jlbooker** [comment]
Fixed, closing.
