### ISSUE TITLE
Update guidelines for contributing

### ISSUE THREAD

**Issue by sheeley** [corejavascript/typeahead.js#48]
It seems as though most of the maintainers here are just that - we're open to PRs, but lack time/desire to implement major features. 

If this is the case, we should update the guidelines to let people know that feature requests will likely not be taken on, and that PRs are the best way to get new features in.

Thoughts @corejavascript/collaborators ?

**Comment by jlbooker** [comment]
Sounds like a good idea @sheeley. I'm mostly in the same situation. I don't have time to develop new features, but I can probably spare enough time to triage issues and review pull requests.

There's some other updates that need to be made to the README, so I'll add this to the list when I update that (hopefully soon).
