### ISSUE TITLE
How to get id and value on event trigger?

### ISSUE THREAD

**Issue by Locustv2** [corejavascript/typeahead.js#56]
My json:

``` json
[
    {id:1, name:'paul'}, 
    {id:2, name:'jim'}, 
    {id:3, name:'tom'}, 
    {id:4, name:'medor'}, 
    {id:5, name:'janzy'}
]
```

instance:

``` javascript
var bh = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    prefetch: '//localhost/data/names.json',
    identify: function(datum){
        return datum.id;    
    }
});

$('#name').typeahead({"highlight":true}, {
    "name":"name",
    "source":bh,
    "display":"value",
    "limit":10
})
```

event triggers:

``` javascript
$('#name').bind('typeahead:select', function(ev, suggestion){
    console.log(suggestion);
})
```

`suggestion` is an object which contain only the text value (i.e. name). How do i obtain the id?

**Comment by unclescooby** [comment]
I'd say:
    console.log(suggestion.id);

You'll probably need to define a template or set the display to make things work properly.
    "display":"name",

**Comment by unclescooby** [comment]
I'd say:

    console.log(suggestion.id);


You'll probably need to define a template or set the display to make things work properly.

     "display":"name",

**Comment by Locustv2** [comment]
Actually there was something weird going with the browser cache. it cached my first json which did not contain name and id, just the values. i had to clear those content and then i could do `console.log(suggestion.id);`.

Thanks anyways.

**Comment by VishKozus** [comment]
there are some issues with event. i don't know why.

**Comment by unclescooby** [comment]
Yes there are issue with the last version of the plugin. I went back to version 0.10.5 which was working for me without issues.

@Locustv2 : you're welcome. Maybe set TTL:0 while testing to prevent such issues.
