### ISSUE TITLE
Templates aren't functioning properly

### ISSUE THREAD

**Issue by Quaked** [corejavascript/typeahead.js#61]
When using remote with bloodhound the template "notFound" is being overwritten by "suggestion" - why?

**Comment by jlbooker** [comment]
@Quaked It's hard to say without seeing your code. Could you post a JsFiddle that reproduces the issue?

**Comment by Quaked** [comment]
If I knew how to use a remote source with bloodhound in jsFiddle I would.
But to my testing it seems even the most basic setup using bloodhound and a
remote source and trying to utilize the template that's the one which won't
work.

Can you provide one where it does?

**Comment by jlbooker** [comment]
This template is working for me:

```
// Initialize typeahead
    $('#studentSearch.typeahead').typeahead({
        highlight: true,
        hint: true,
        minLength: 0
    },
    {
        name: 'studentSearch',
        display: 'name',
        limit: 5,
        source: studentSearchSource.ttAdapter(),
        templates: {
            suggestion: function(suggestion) {
                return('<p>' + suggestion.name + "<br />" + suggestion.student_id + " &bull; " + suggestion.username + "</p>");
            },
            empty: function() {
                return('<p style="margin: 0 20px 5px 20px; padding: 3px 0;" class="text-muted">No results found.</p>');
            }
        }
    },
    {
        name: 'previousSearch',
        display: 'name',
        limit: 5,
        async: false,
        source: previousSearchProvider,
        templates: {
            suggestion: function(suggestion) {
                return('<p>' + suggestion.name + "<br />" + suggestion.student_id + " &bull; " + suggestion.username + "</p>");
            },
            header: function() {
                return ('<h5 style="margin: 0 20px 5px 20px; padding: 3px 0; border-bottom: 1px solid #ccc;">Previous Searches</h5>');
            }
        }
    }
    );
```

**Comment by Quaked** [comment]
Well, I don't doubt it. However the actual source of previousSearchProvider
is omitted and that seems to be without bloodhound. Care to show an example
having bloodhound and showing the remote function/source as the issue I'm
having seems to be specific to that.

I had to do some trickery inside the other templates to make up for it not
functioning...

**Comment by unclescooby** [comment]
@jlbooker  which plugin version are you using?
As I'm seeing template rendering issues with v.0.11.1 but not with v.0.10.5
#57

**Comment by jlbooker** [comment]
@unclescooby The project I'm using it most heavily in (and took the above example from) is running 0.11.1. It actually looks like the last official Twitter release installed via Bower, before this fork took off.

**Comment by jlbooker** [comment]
@Quaked Here's one of my Bloodhound sources:

```
// Suggestion provider for server-provided results
    var studentSearchSource = new Bloodhound({
        name: 'remoteSearch',
        datumTokenizer: function(datum){
            var nameTokens      = Bloodhound.tokenizers.obj.whitespace('name');
            var userIdTokens    = Bloodhound.tokenizers.obj.whitespace('user_id');
            var usernameTokens  = Bloodhound.tokenizers.obj.whitespace('username');

            return nameTokens.concat(userIdTokens).concat(usernameToekns);
        },
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        remote: {
            url: 'index.php?action=GetUsernameSuggestions&query=%QUERY',
            wildcard: '%QUERY',
            rateLimitWait: 1000,
            rateLimitBy: 'throttle'
        }
    });
```

**Comment by Quaked** [comment]
Thanks!

I isolates the issue to be when not having results one needs to make sure
then json response is an empty json string or you either get length of
undefined or you get a result that is empty which won't trigger the
template.

So basically I made sure if no results are found an empty array is encoded
in json and being output to trigger it. Your examples were helpful though!

A suggestion would be adding some error handling console log for such
things or maybe I missed something in the docs. Anyhow thanks for your help!
