### ISSUE TITLE
Bloodhound not returning all results

### ISSUE THREAD

**Issue by yanickrochon** [corejavascript/typeahead.js#67]
This is an issue [I already reported](https://github.com/twitter/typeahead.js/issues/1486), yesterday, but since it also applies to this branch (which is apparantly the active branch), I'm also reporting it here.

**Comment by yanickrochon** [comment]
This is confirmed as solved with the most recent JS in this repository. When will this be pushed to `bower` and all? (See issue #55)

**Comment by jlbooker** [comment]
Duplicate of #43  and fixed in #52

**Comment by jlbooker** [comment]
We're working on a new NPM package for the registry. See #72
