### ISSUE TITLE
Nuget Support

### ISSUE THREAD

**Issue by Claty** [corejavascript/typeahead.js#70]
Will the library be added to the Nuget repository?

**Comment by jlbooker** [comment]
Seems to be referring to: https://www.nuget.org/  ([Howto on publishing a package](http://docs.nuget.org/Create/creating-and-publishing-a-package))

I don't have a .NET environment (nor Visual Studio, which seems to be necessary) to test this in. Can't speak for the other maintainers here, but my first guess would be "it's not likely". I'm not sure you'll find much interest in .NET here.  Unless you want to take the time to create and maintain the NuGet package, which you should feel free to do! :smile:

**Comment by namtab00** [comment]
+1 for NuGet, .NET shop here using this revived repo.

...though for client libs I've migrated to bower as Microsoft recommends jumping on the js managers bandwagon starting with Visual Studio 2015 (it handled npm, gulp & bower decently)

Still, some folk may be stuck with policy enforced NuGet for client packages also.

Sorry I can't really help with the NuGet packaging though, I never did any of that, just my 2 cents...

**Comment by jlbooker** [comment]
I think I'm going to close this for now. It looks like Visual Studio has support for NPM (https://webtooling.visualstudio.com/package-managers/npm/) and it's becoming the widely accepted standard for JS package management on both Windows and Linux platforms. Unless there's a huge surge in demand for NuGet, I think we should standardize on NPM.
