### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by Frisbetarian** [corejavascript/typeahead.js#72]
Noticed that pulling the module from NPM wasn't working so I went ahead and forked this repo and put it up on NPM.

https://www.npmjs.com/package/wamda-typeahead

**Comment by barsh** [comment]
Is this fork of typeahead still being maintained?  If so, why is it not on NPM?

**Comment by jcrben** [comment]
The reality is that it isn't being maintained all that well. Do either of you want to pitch in?

**Comment by MarkHerhold** [comment]
@jcrben I would like to help. I use typeahead for multiple projects and need to ensure that it is well maintained.

**Comment by ziedmahdi** [comment]
I maybe wrong but I saw corejs-typeahead on npm so I think this issue has to be closed.

**Comment by svbergerem** [comment]
Here is a link to the package: https://www.npmjs.com/package/corejs-typeahead

**Comment by MarkHerhold** [comment]
It looks like it wasn't published by the corejavascript folks, but rather by `~mariusz-kraj`. I don't know who this is. Maybe [this person](https://github.com/mariusz-kraj)?

At any rate, I don't trust it.

https://www.npmjs.com/~mariusz-kraj

**Comment by jlbooker** [comment]
Just realize we have two issues open regarding the same general topic: releasing a new NPM package. I'm going to close this issue in favor of the earlier #55. Let's take the discussion over there.
