### ISSUE TITLE
Handlebars template not rendering correctly after move from twitter version

### ISSUE THREAD

**Issue by KrunchMuffin** [corejavascript/typeahead.js#75]
Here is my code which worked fine. I updated because of the limit issue. Now it's not rendering correctly.

```
    var custSearch = new Bloodhound({
      datumTokenizer: function(d) { return d.tokens; }, //Bloodhound.tokenizers.obj.whitespace('fullname'),
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      remote: {
        url: '/com/franchise/customer.cfc?method=getNameSearch&query=%QUERY',
        wildcard: '%QUERY'
      }
    });

    custSearch.initialize();

    $("#CustSearch").typeahead({
        minLength: 3,
        highlight: true
    },
    {
        name: "Cust-Search",
        source: custSearch.ttAdapter(),
        limit: 25,
        templates: {
                empty: [
                    '<div class="empty-message">',
                    'No matches found',
                    '</div>'
                ].join('\n'),
                suggestion: Handlebars.compile([
                    '<p class="user-type">{{type}}</p>',
                    '<p class="user-name">{{fullname}} {{#if company}}({{company}}){{/if}}</p>',
                    '<p class="user-info">{{info}}</p>',
                    '{{#if address}}<p class="user-info">{{address}}</p>{{/if}}'
                ].join(''))
            }
    })
    .on("typeahead:select", onSelected);
```

here is how it is rendering

![image](https://cloud.githubusercontent.com/assets/1037197/14429965/ab45d2aa-ffcd-11e5-953b-56c14fe959b3.png)

![image](https://cloud.githubusercontent.com/assets/1037197/14429981/bc5c47a4-ffcd-11e5-99b1-0a2abf1f93a7.png)

**Comment by KrunchMuffin** [comment]
I tried changing to a regular template

    templates: {
	    notFound: function() {
		    return('<div class="empty-message">No matches found</div>');
        },
        suggestion: function(suggestion) { return('<span class="user-type">'+suggestion.type+'</span><br><span class="user-name">'+suggestion.fullname + ' ' +suggestion.company+'</span><p class="user-info">'+suggestion.info+'</p><p class="user-info">'+suggestion.address+'</p>');
        }
    }

but it still doe snot work. So I tried cutting  down till it did. Turns out it stops at the last end tag no matter if it is `</p>` or `</span>` or what. Not sure if that is a bug or intentional.

    suggestion: function(suggestion) { return('<span class="user-type">foo</span>'+suggestion.type+'</span><br><span class="user-name">'+suggestion.fullname + ' ' +suggestion.company+'</span><p class="user-info">'+suggestion.info+'</p><p class="user-info">'+suggestion.address+'</p>');
                    }

**Comment by onokazu** [comment]
Try:

`suggestion: function(suggestion) { return('<div><span class="user-type">foo</span>'+suggestion.type+'</span><br><span class="user-name">'+suggestion.fullname + ' ' +suggestion.company+'</span><p class="user-info">'+suggestion.info+'</p><p class="user-info">'+suggestion.address+'</p></div>');`

**Comment by jlbooker** [comment]
Possibly related to #57 and #61. Please try the solutions suggested there.

In the meantime, closing due to age/inactivity.
