### ISSUE TITLE
Why several datasets = several queries ?

### ISSUE THREAD

**Issue by AlexCppns** [corejavascript/typeahead.js#80]
For performance, our backend does one query and groups the results in 2 sections, it seems like the plugin is built to do one query per section.

**Comment by jlbooker** [comment]
Hi @AlexCppns. You are correct, there is one query per source. You are assuming that all of the sources will be on the same server and/or URL. This is not necessarily the case. Multiple disparate sources can be used, so it's necessary to send a request for each source (even if they happen to be on the same server).

To handle the the case you describe, I'd suggest using a single source endpoint that returns both result sets combined.
