### ISSUE TITLE
bower.json configuration ignore

### ISSUE THREAD

**Issue by Claty** [corejavascript/typeahead.js#83]
Im not sure how many of you install this package through bower, but when i do it installs the entire git directory into my project folder. Anyone against adding the ignore attribute in the bower.json so that when you install the package you only get the contents in the dist directiory

**Comment by jlbooker** [comment]
@Claty Sounds fine to me, as that seems to be the convention with other bower packages.

I'm interested that you use Bower to install it, as there's discussion of dropping the Bower package and just using npm.

**Comment by Claty** [comment]
@jlbooker ASP.NET 5 managers client side packages with bower by default. Whats the reason for dropping bower?

**Comment by jlbooker** [comment]
@Claty  See #74 and related issue #47. NPM was running bower install for no apparent reason. We've now separated the bower installation, so that it is no longer run by npm install.

Feel free to submit a pull request for your request above. Sounds like it wouldn't be a problem.

**Comment by Claty** [comment]
@jlbooker we moved away from bower and now using npm

**Comment by jlbooker** [comment]
Thanks for the update @Claty. I'll go ahead a close this issue. Feel free to re-open if you need to.
