### ISSUE TITLE
Update entry on rails-assets.org

### ISSUE THREAD

**Issue by trivektor** [corejavascript/typeahead.js#85]
This fix https://github.com/corejavascript/typeahead.js/commit/bf60a907479e2dc1bfdbe4704377164719e229a8 doesn't seem to be included in the version of this library on rails-assets.org

https://rails-assets.org/#/components/corejs-typeahead

**Comment by themilkman** [comment]
Yeah, a version bump would be great :-)

**Comment by jlbooker** [comment]
Working on a new release now. Please see #55. I'll see about updating the rails site when the next version is available.

**Comment by jlbooker** [comment]
Looks likes updating the rails-assets site requires updating the bower package. Someone else ('corejavascript') owns the bower package. @lenovouser is that you? Could you update that bower package to v1.0.1?

**Comment by svbergerem** [comment]
rails-assets already has been updated: https://rails-assets.org/#/components/corejs-typeahead. (v1.0.1 is available there)

**Comment by jlbooker** [comment]
Ahh, yep. Looks like I had a cached copy of the page. I see it has updated now. Thanks @svbergerem!
