### ISSUE TITLE
typeahead:select event does not pass dataset name

### ISSUE THREAD

**Issue by onokazu** [corejavascript/typeahead.js#89]
The typeahead:selected event, when triggered, used to pass the name of the dataset of the item selected as the third parameter, but it doesn't anymore for the typeahead:select event. How do we know the name of the dataset the selected item belongs to?

**Comment by jlbooker** [comment]
@onokazu Is this related (and possibly fixed by) #65?

**Comment by jlbooker** [comment]
Duplicate of #63 and #58
