### ISSUE TITLE
Feature Request: Bloodhound Edge Ngram Tokenizer

### ISSUE THREAD

**Issue by rich186** [corejavascript/typeahead.js#91]
I find the current whitespace and nonword tokenizers in Bloodhound useful but I think a simple edge ngram tokenizer (à la Elasticsearch) would be a great addition, and is very suited to autocomplete queries.

To clarify, given the input `"Foo bar"`, the tokenizer would return the following:

```
["F", "Fo", "Foo", "b", "ba", "bar"]
```

I already submitted a PR to the previous Twitter repo [here](https://github.com/twitter/typeahead.js/pull/1568) but then discovered it's no longer maintained. If you think it'd be worthwhile addition let me know and i'll submit another PR here.

**Comment by jlbooker** [comment]
@rich186 Sounds like a good contribution to me. Would you mind rebasing your PR to this fork and submitting a new PR here?

**Comment by rich186** [comment]
@jlbooker Sure, just submitted PR #93

**Comment by jlbooker** [comment]
PR Merged, thanks again!
