### ISSUE TITLE
doesn't work well with bootstrap

### ISSUE THREAD

**Issue by ajoslin103** [corejavascript/typeahead.js#94]
when you have a bootstrap input 
```
<input class="col-sm-7 form-control" id="typeahead-race" type="text"></input>
```

it gets wrapped in a span which breaks the responsive class (col-sm-7)
```
<span class="twitter-typeahead">
   <input class="col-sm-7 form-control" id="typeahead-race" type="text"></input>
```

I don't know how to fix this, but offering className support on the span would help

**Comment by jlbooker** [comment]
Hi @ajoslin103 ,

Try wrapping the input in a div or a span and setting the responsive class on that element, instead of on the input. For example:

```
<div class="col-sm-7">
    <input class="col-sm-7 form-control" id="typeahead-race" type="text"></input>
</div>
```

With this markup, when the Typeahead adds the wrapping span class, it won't change the bootstrap columns.
