### ISSUE TITLE
Typeahead matching all values when using remote source data

### ISSUE THREAD

**Issue by swimboy** [corejavascript/typeahead.js#99]
I have a very simple typeahead configuration. My json request returns an array of strings, no extra data, so my code is very simple:
```javascript
$(document).ready(function(){
    var search1 = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.whitespace,
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        remote: {
            url: '/customers/search1'
        }
    });
    $(' .typeahead').typeahead({highlight: true},{
        name: 'search1',
        source: search1,
        limit: 10
    });
});
```
When I access this, the dropdown shows all records, even the ones that don't match. I have highlighting enabled, and I can see it highlighting the records that match, but it doesn't eliminate the records that don't.

If I do a `curl -H "Accept:application/json" http://mysite.local/customers/search1` and paste the results into a variable, and use that variable as a local source, the dropdown works as expected. If I change the `remote` datasource to `prefetch` it also works, but never updates if I add records.

The result of my curl request looks like this:
```
[
    "5  Acme City Management 1",
    "6  P \u0026 B Restaurant 5",
    "9  City of Springfield Housing 12",
    "10  General Hospital 34",
    "11  Test Customer 778.1"
]
```

Is there something I'm missing?

**Comment by jlbooker** [comment]
Your remote URL should only be returning results that match. The searching/matching is done server-side.

If I type "Acme" into your typeahead, the server should only return ```["5  Acme City Management 1"]``` and the typeahead component will highlight it like "**Acme** City Management 1".
